<a href="https://colab.research.google.com/github/Ashutosh-Singh2209/Logistic-Regression-on-Titanic-Dataset/blob/main/Logistic_Regression_on_Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Logistic Regression on Titanic Dataset

I have been given a training dataset CSV file with X train and Y train data, and an X test file. My task is to use Logistic Regression as a training algorithm and come up with predictions for the given data.

To accomplish this, I will follow these steps:

1. Import the necessary libraries and the dataset using the sklearn library.
2. Perform data preprocessing, if required, for the training dataset.
3. Fit the Logistic Regression model to the training data.
4. Use the trained model to make predictions on the X test data.
5. Generate a CSV file with the predicted results for the X test data, with only one column and no headers.

# **VARIABLE DESCRIPTIONS**

1. **Pclass:** Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
2. **Survival:** Survival (0 = No; 1 = Yes)
3. **Name:** Name
4. **Sex:** Sex
5. **Age:** Age
6. **SibSp:** Number of Siblings/Spouses Aboard
7. **Parch:** Number of Parents/Children Aboard
8. **Ticket:** Ticket Number
9. **Fare:** Passenger Fare (British pound)
10. **Cabin:** Cabin
11. **Embarked:** Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)

### Import Libraries and Read CSV Files

In the next cell, I will import the `pandas` and `numpy` libraries and read the provided CSV files.

In [14]:
import numpy as np

In [15]:
import pandas as pd
data = pd.read_csv('train.csv', delimiter=',')
data.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.000,NaN,S,1
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.050,NaN,S,0
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.000,NaN,S,0
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S,0
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S,0

In [16]:
X = pd.read_csv('test.csv', delimiter=',')
X.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,2,"Davies, Master. John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S
1,1,"Leader, Dr. Alice (Farnham)",female,49.0,0,0,17465,25.9292,D17,S
2,3,"Kilgannon, Mr. Thomas J",male,NaN,0,0,36865,7.7375,NaN,Q
3,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
4,1,"McGough, Mr. James Robert",male,36.0,0,0,PC 17473,26.2875,E25,S

Next, I will display the shape of the datasets and identify the number of missing values in each column.

In [17]:
data.shape, X.shape

((668, 11), (223, 10))

In [18]:
data.isna().sum()

Pclass        0
Name          0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      1
Survived      0
dtype: int64

In [19]:
X.isna().sum()

Pclass        0
Name          0
Sex           0
Age          45
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       173
Embarked      1
dtype: int64

Analyzing the "Ticket" Column

In [20]:
set(data['Ticket'])

{'110152',
 '110413',
 '110465',
 '110564',
 '111240',
 '111361',
 '111369',
 '111426',
 '111427',
 '111428',
 '112050',
 '112052',
 '112058',
 '112277',
 '113028',
 '113043',
 '113051',
 '113055',
 '113056',
 '113059',
 '113501',
 '113503',
 '113505',
 '113509',
 '113572',
 '113760',
 '113767',
 '113773',
 '113776',
 '113781',
 '113784',
 '113786',
 '113788',
 '113789',
 '113794',
 '113798',
 '113800',
 '113803',
 '113804',
 '113806',
 '11668',
 '11751',
 '11752',
 '11753',
 '11755',
 '11765',
 '11769',
 '11771',
 '11774',
 '11813',
 '11967',
 '12233',
 '12460',
 '12749',
 '13049',
 '13502',
 '13507',
 '13509',
 '13568',
 '14313',
 '14973',
 '1601',
 '16966',
 '17421',
 '17453',
 '17463',
 '17464',
 '17466',
 '17474',
 '19877',
 '19928',
 '19943',
 '19950',
 '19952',
 '19972',
 '19988',
 '19996',
 '211536',
 '218629',
 '220367',
 '220845',
 '2223',
 '223596',
 '226875',
 '228414',
 '229236',
 '230080',
 '230136',
 '230433',
 '230434',
 '231919',
 '231945',
 '233639',
 '233866',
 '234360',
 '234604',
 '234686',
 '234818',
 '236171',
 '236852',
 '236853',
 '237442',
 '237565',
 '237668',
 '237736',
 '237789',
 '237798',
 '239853',
 '239854',
 '239855',
 '239856',
 '24160',
 '243847',
 '244270',
 '244310',
 '244358',
 '244361',
 '244367',
 '244373',
 '248698',
 '248706',
 '248723',
 '248727',
 '248733',
 '248738',
 '248740',
 '248747',
 '250644',
 '250646',
 '250647',
 '250648',
 '250649',
 '250651',
 '250652',
 '250653',
 '250655',
 '2620',
 '2624',
 '2626',
 '2627',
 '2628',
 '2629',
 '2631',
 '26360',
 '2641',
 '2647',
 '2648',
 '2649',
 '2650',
 '2651',
 '2653',
 '2659',
 '2661',
 '2663',
 '2665',
 '2666',
 '2667',
 '2668',
 '2669',
 '26707',
 '2671',
 '2672',
 '2677',
 '2678',
 '2680',
 '2683',
 '2685',
 '2686',
 '2687',
 '2689',
 '2691',
 '2694',
 '2695',
 '2699',
 '2700',
 '27042',
 '27267',
 '27849',
 '28213',
 '28220',
 '28228',
 '28403',
 '28424',
 '28664',
 '29011',
 '2908',
 '29103',
 '29104',
 '29105',
 '29106',
 '29108',
 '2926',
 '29750',
 '29751',
 '3101264',
 '3101277',
 '3101278',
 '3101281',
 '3101295',
 '3101296',
 '31027',
 '31028',
 '312992',
 '312993',
 '31418',
 '315084',
 '315086',
 '315088',
 '315089',
 '315096',
 '315098',
 '315151',
 '315153',
 '330877',
 '330919',
 '330923',
 '330931',
 '330935',
 '330979',
 '330980',
 '334912',
 '335097',
 '335677',
 '336439',
 '3411',
 '341826',
 '34218',
 '342826',
 '343095',
 '343120',
 '343275',
 '343276',
 '345364',
 '345572',
 '345763',
 '345764',
 '345765',
 '345767',
 '345769',
 '345770',
 '345773',
 '345774',
 '345779',
 '345780',
 '345783',
 '3460',
 '347054',
 '347060',
 '347063',
 '347064',
 '347067',
 '347069',
 '347073',
 '347074',
 '347076',
 '347077',
 '347080',
 '347081',
 '347082',
 '347083',
 '347088',
 '347089',
 '347466',
 '347468',
 '347470',
 '347742',
 '347743',
 '348121',
 '348123',
 '348124',
 '349201',
 '349203',
 '349204',
 '349205',
 '349206',
 '349207',
 '349209',
 '349212',
 '349213',
 '349214',
 '349215',
 '349216',
 '349218',
 '349219',
 '349221',
 '349223',
 '349225',
 '349228',
 '349231',
 '349233',
 '349234',
 '349236',
 '349237',
 '349239',
 '349240',
 '349241',
 '349242',
 '349243',
 '349245',
 '349246',
 '349247',
 '349248',
 '349251',
 '349253',
 '349254',
 '349256',
 '349257',
 '349909',
 '349912',
 '350026',
 '350034',
 '350036',
 '350046',
 '350047',
 '350048',
 '350050',
 '350404',
 '350407',
 '350417',
 '35273',
 '35281',
 '35851',
 '35852',
 '358585',
 '362316',
 '363291',
 '363294',
 '363592',
 '364498',
 '364499',
 '364500',
 '364511',
 '364512',
 '364516',
 '364846',
 '364849',
 '364850',
 '364851',
 '365222',
 '36568',
 '367226',
 '367228',
 '367229',
 '367230',
 '367231',
 '368323',
 '36864',
 '36866',
 '368703',
 '36928',
 '36947',
 '36967',
 '36973',
 '370129',
 '370365',
 '370369',
 '370370',
 '370371',
 '370373',
 '370375',
 '370377',
 '371060',
 '371110',
 '371362',
 '372622',
 '373450',
 '374887',
 '374910',
 '376564',
 '382652',
 '384461',
 '386525',
 '392091',
 '392092',
 '392096',
 '394140',
 '4133',
 '4134',
 '4136',
 '4137',
 '4138',
 '4579',
 '54636',
 '65303',
 '65306',
 '6563',
 '693',
 '695',
 '7534',
 '7540',
 '7546',
 '7553',
 '7598',
 'A./5. 2152',
 'A./5. 3235',
 'A.5. 18509',
 'A/4 45380',
 'A/4 48871',
 'A/4. 20589',
 'A/4. 34244',
 'A/4. 39886',
 'A/5 21172',
 'A/5 21173',
 'A/5 2466',
 'A/5 2817',
 'A/5 3540',
 'A/5 3594',
 'A/5 3902',
 'A/5. 10482',
 'A/5. 2151',
 'A/5. 3336',
 'A/5. 3337',
 'C 17369',
 'C 7076',
 'C 7077',
 'C.A. 17248',
 'C.A. 18723',
 'C.A. 2315',
 'C.A. 24579',
 'C.A. 24580',
 'C.A. 2673',
 'C.A. 29566',
 'C.A. 31026',
 'C.A. 31921',
 'C.A. 33111',
 'C.A. 33112',
 'C.A. 33595',
 'C.A. 34260',
 'C.A. 34651',
 'C.A. 37671',
 'C.A. 5547',
 'C.A. 6212',
 'CA 2144',
 'CA. 2314',
 'CA. 2343',
 'F.C.C. 13528',
 'F.C.C. 13529',
 'F.C.C. 13531',
 'LINE',
 'P/PP 3381',
 'PC 17318',
 'PC 17474',
 'PC 17475',
 'PC 17476',
 'PC 17477',
 'PC 17482',
 'PC 17483',
 'PC 17485',
 'PC 17569',
 'PC 17572',
 'PC 17582',
 'PC 17585',
 'PC 17590',
 'PC 17592',
 'PC 17593',
 'PC 17595',
 'PC 17596',
 'PC 17597',
 'PC 17599',
 'PC 17601',
 'PC 17604',
 'PC 17605',
 'PC 17608',
 'PC 17610',
 'PC 17611',
 'PC 17612',
 'PC 17755',
 'PC 17756',
 'PC 17757',
 'PC 17758',
 'PC 17759',
 'PC 17760',
 'PC 17761',
 'PP 4348',
 'PP 9549',
 'S.C./A.4. 23567',
 'S.C./PARIS 2079',
 'S.O./P.P. 3',
 'S.O./P.P. 751',
 'S.O.C. 14879',
 'S.O.P. 1166',
 'S.W./PP 752',
 'SC 1748',
 'SC/AH 29037',
 'SC/AH 3085',
 'SC/AH Basle 541',
 'SC/PARIS 2131',
 'SC/PARIS 2146',
 'SC/PARIS 2149',
 'SC/PARIS 2167',
 'SC/Paris 2123',
 'SC/Paris 2163',
 'SO/C 14885',
 'SOTON/O.Q. 3101305',
 'SOTON/O.Q. 3101306',
 'SOTON/O.Q. 3101310',
 'SOTON/O.Q. 3101311',
 'SOTON/O.Q. 3101312',
 'SOTON/O.Q. 392078',
 'SOTON/O.Q. 392087',
 'SOTON/O2 3101287',
 'SOTON/OQ 3101316',
 'SOTON/OQ 3101317',
 'SOTON/OQ 392076',
 'SOTON/OQ 392082',
 'SOTON/OQ 392086',
 'SOTON/OQ 392089',
 'SOTON/OQ 392090',
 'STON/O 2. 3101269',
 'STON/O 2. 3101273',
 'STON/O 2. 3101274',
 'STON/O 2. 3101280',
 'STON/O 2. 3101286',
 'STON/O 2. 3101289',
 'STON/O 2. 3101292',
 'STON/O 2. 3101294',
 'STON/O2. 3101271',
 'STON/O2. 3101279',
 'SW/PP 751',
 'W./C. 14263',
 'W./C. 6607',
 'W./C. 6608',
 'W/C 14208',
 'WE/P 5735'}

I am planning to incorporate the ticket number as a feature in my analysis.

In [21]:
data['Ticket'] = data['Ticket'].apply(lambda x : x.split()[-1])
X['Ticket'] = X['Ticket'].apply(lambda x : x.split()[-1])

In [22]:
data['Ticket'][ data['Ticket'].apply( lambda x : not (x.isdigit()) ) ]

117    LINE
301    LINE
526    LINE
Name: Ticket, dtype: object

In [23]:
def f(s) :
  if s.isdigit() :
    return int(s)
  else :
    return 0

data['Ticket'] = data['Ticket'].apply(lambda x : f(x))
X['Ticket'] = X['Ticket'].apply(lambda x : f(x))

I will now separate the Y values from the dataset.

In [24]:
# splitting training_df into training_df X values and Y_values
Y_data = data['Survived'].values
Y_data

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1])

In [25]:
data.drop('Survived', axis=1, inplace=True)
data.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.000,NaN,S
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,2466,8.050,NaN,S
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.000,NaN,S
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,392076,7.050,NaN,S

Next, I will proceed to handle the missing values as part of the data cleaning process.

In [26]:
# Impute Age with median
data['Age'].fillna(data['Age'].median(), inplace=True)

# Impute Embarked with mode
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

# Impute Age and Embarked for X using values from data
X['Age'].fillna(X['Age'].median(), inplace=True)
X['Embarked'].fillna(X['Embarked'].mode()[0], inplace=True)

In [27]:
# now check the missing values again
print(data.isna().sum())
print()
print(X.isna().sum())

Pclass        0
Name          0
Sex           0
Age           0
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       514
Embarked      0
dtype: int64

Pclass        0
Name          0
Sex           0
Age           0
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       173
Embarked      0
dtype: int64

Cabin column in both testing and training data have too many missing values, so we need to drop them.

In [28]:
data.drop('Cabin', axis=1, inplace=True)
X.drop('Cabin', axis=1, inplace=True)

In [29]:
# now check the missing values again
print(data.isna().sum())
print()
print(X.isna().sum())

Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

Now we need to do Label Encoding for non-numeric datapoints.

In [30]:
data.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.000,S
1,3,"Williams, Mr. Howard Hugh ""Harry""",male,29.0,0,0,2466,8.050,S
2,2,"Morley, Mr. Henry Samuel (""Mr Henry Marshall"")",male,39.0,0,0,250655,26.000,S
3,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,S
4,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,392076,7.050,S

To do the Label Encoding, we need to combine the two datasets. But 1st we drop the name column, as it has no significance in training the Logistic Regression model.

In [31]:
data.drop('Name', axis=1, inplace=True)
X.drop('Name', axis=1, inplace=True)

In [32]:
X.head()

   Pclass     Sex   Age  SibSp  Parch  Ticket     Fare Embarked
0       2    male   8.0      1      1   33112  36.7500        S
1       1  female  49.0      0      0   17465  25.9292        S
2       3    male  27.0      0      0   36865   7.7375        Q
3       2  female  24.0      2      1  243847  27.0000        S
4       1    male  36.0      0      0   17473  26.2875        S

Combining the two datasets.

In [33]:
from sklearn.preprocessing import LabelEncoder

# Combine training and testing data for encoding
combined_df = pd.concat([data, X], ignore_index=True)

# Initialize LabelEncoders for 'Sex', 'Embarked', and 'Ticket' columns
label_encoder_sex = LabelEncoder()
label_encoder_embarked = LabelEncoder()
# label_encoder_ticket = LabelEncoder()

# Fit and transform categorical columns
combined_df['Sex_Encoded'] = label_encoder_sex.fit_transform(combined_df['Sex'])
combined_df['Embarked_Encoded'] = label_encoder_embarked.fit_transform(combined_df['Embarked'])
# combined_df['Ticket_Encoded'] = label_encoder_ticket.fit_transform(combined_df['Ticket'])

# Split back into training and testing data
data_encoded = combined_df.iloc[:len(data)]
X_encoded = combined_df.iloc[len(data):]

# Use training_df_encoded and testing_df_encoded for further analysis

In [34]:
data_encoded.head()

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_Encoded,Embarked_Encoded
0,2,female,29.0,1,0,228414,26.000,S,0,2
1,3,male,29.0,0,0,2466,8.050,S,1,2
2,2,male,39.0,0,0,250655,26.000,S,1,2
3,3,female,29.0,0,4,349909,21.075,S,0,2
4,3,male,25.0,0,0,392076,7.050,S,1,2

In [35]:
X_encoded.head()

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_Encoded,Embarked_Encoded
668,2,male,8.0,1,1,33112,36.7500,S,1,2
669,1,female,49.0,0,0,17465,25.9292,S,0,2
670,3,male,27.0,0,0,36865,7.7375,Q,1,1
671,2,female,24.0,2,1,243847,27.0000,S,0,2
672,1,male,36.0,0,0,17473,26.2875,S,1,2

In [36]:
X_encoded.reset_index(drop=True, inplace=True)
X_encoded.head()

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_Encoded,Embarked_Encoded
0,2,male,8.0,1,1,33112,36.7500,S,1,2
1,1,female,49.0,0,0,17465,25.9292,S,0,2
2,3,male,27.0,0,0,36865,7.7375,Q,1,1
3,2,female,24.0,2,1,243847,27.0000,S,0,2
4,1,male,36.0,0,0,17473,26.2875,S,1,2

Now get X_train and X_test

In [37]:
# Define the columns you want to include
selected_columns = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_Encoded', 'Embarked_Encoded']

# Extract values of selected columns for training data
X_data = data_encoded[selected_columns].values

# Extract values of selected columns for testing data
X_ = X_encoded[selected_columns].values

In [38]:
X_

array([[  2.    ,   8.    ,   1.    , ...,  36.75  ,   1.    ,   2.    ],
       [  1.    ,  49.    ,   0.    , ...,  25.9292,   0.    ,   2.    ],
       [  3.    ,  27.    ,   0.    , ...,   7.7375,   1.    ,   1.    ],
       ...,
       [  1.    ,  17.    ,   1.    , ..., 108.9   ,   0.    ,   0.    ],
       [  3.    ,  43.    ,   0.    , ...,   6.45  ,   1.    ,   2.    ],
       [  2.    ,  36.5   ,   0.    , ...,  26.    ,   1.    ,   2.    ]])

I will now split the `X_data` and `Y_data` into `X_train`, `X_test`, `Y_train`, and `Y_test`.

In [39]:
from sklearn.model_selection import train_test_split

# Splitting the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.3, random_state=42)

# Print the shapes of the resulting arrays
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

X_train shape: (467, 7)
X_test shape: (201, 7)
Y_train shape: (467,)
Y_test shape: (201,)

Now using the Logisting Regression and train LogisticRegression algorithm on training data.

In [40]:
from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
logreg_model = LogisticRegression(C=1, max_iter=1000, tol=0.0001, penalty='l2', random_state=42)

# Fit the model on the training data
logreg_model.fit(X_train, Y_train)

# Evaluate the model
# Calculate accuracy using the score method
train_accuracy = logreg_model.score(X_train, Y_train)
test_accuracy = logreg_model.score(X_test, Y_test)
print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

Training Accuracy: 0.7944325481798715
Testing Accuracy: 0.7910447761194029

We are achieving approximately 80% accuracy on both splits of the data.

I will now predict the values for the given `test.csv` and save the results in a `.csv` file.

In [41]:
# Predict on the testing data
Y = logreg_model.predict(X_)

In [42]:
# save Y_pred to a csv file
np.savetxt("Y_pred.csv", Y, delimiter=",")